In [0]:
from google.colab import drive
drive.mount('/content/gdrive')

In [0]:
import pandas as pd
df=pd.read_csv('gdrive/My Drive/Consumer_Complaints.csv')

In [0]:
df.head(10)

Date received                      Product  \
0    03/12/2014                     Mortgage   
1    01/19/2017                 Student loan   
2    04/06/2018  Credit card or prepaid card   
3    06/08/2014                  Credit card   
4    09/13/2014              Debt collection   
5    11/13/2013                     Mortgage   
6    06/16/2015              Debt collection   
7    08/22/2018                     Mortgage   
8    11/13/2015                     Mortgage   
9    10/21/2014                     Mortgage   

                                  Sub-product  \
0                              Other mortgage   
1              Federal student loan servicing   
2  General-purpose credit card or charge card   
3                                         NaN   
4                                 Credit card   
5      Conventional adjustable mortgage (ARM)   
6                                     Medical   
7                  Conventional home mortgage   
8                              Other mortgage   
9                 Conventional fixed mortgage   

                                      Issue  \
0  Loan modification,collection,foreclosure   
1        Dealing with my lender or servicer   
2        Other features, terms, or problems   
3                                Bankruptcy   
4                     Communication tactics   
5  Loan servicing, payments, escrow account   
6       Improper contact or sharing of info   
7            Trouble during payment process   
8  Loan modification,collection,foreclosure   
9  Loan modification,collection,foreclosure   

                                Sub-issue  \
0                                     NaN   
1  Received bad information about my loan   
2                           Other problem   
3                                     NaN   
4              Frequent or repeated calls   
5                                     NaN   
6   Contacted employer after asked not to   
7                                     NaN   
8                                     NaN   
9                                     NaN   

                        Consumer complaint narrative  \
0                                                NaN   
1  When my loan was switched over to Navient i wa...   
2  I tried to sign up for a spending monitoring p...   
3                                                NaN   
4                                                NaN   
5                                                NaN   
6                                                NaN   
7  My mortgage is with BB & T Bank, recently I ha...   
8                                                NaN   
9                                                NaN   

                             Company public response  \
0                                                NaN   
1                                                NaN   
2                                                NaN   
3                                                NaN   
4                                                NaN   
5                                                NaN   
6  Company believes it acted appropriately as aut...   
7  Company has responded to the consumer and the ...   
8  Company believes it acted appropriately as aut...   
9                                                NaN   

                             Company State ZIP code            Tags  \
0               M&T BANK CORPORATION    MI    48382             NaN   
1            Navient Solutions, LLC.    LA      NaN             NaN   
2  CAPITAL ONE FINANCIAL CORPORATION    VA      NaN  Older American   
3           AMERICAN EXPRESS COMPANY    ID    83854  Older American   
4                     CITIBANK, N.A.    VA    23233             NaN   
5                       U.S. BANCORP    MN    48322             NaN   
6        California Accounts Service    CA    92111             NaN   
7                   BB&T CORPORATION    IN      NaN             NaN   
8                 Aldridge Pite, LLP    CA    

In [0]:
from keras.preprocessing.text import text_to_word_sequence
import pandas as pd
from keras.preprocessing.text import Tokenizer
import numpy as np


from keras.preprocessing import sequence
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.layers import Embedding
from keras.layers import Conv1D, GlobalMaxPooling1D

In [0]:
import pandas as pd
d = pd.read_csv("gdrive/My Drive/Consumer_Complaints.csv", 
                 usecols=[1, 5],
                dtype={'consumer_complaint_narrative': object})

In [0]:
d.head(4)

Product  \
0                     Mortgage   
1                 Student loan   
2  Credit card or prepaid card   
3                  Credit card   

                        Consumer complaint narrative  
0                                                NaN  
1  When my loan was switched over to Navient i wa...  
2  I tried to sign up for a spending monitoring p...  
3                                                NaN

In [0]:
# Only interested in data with consumer complaints

d=d[d['Consumer complaint narrative'].notnull()]
d=d[d['Product'].notnull()]
d.reset_index(drop=True,inplace=True)
x = d.iloc[:, 1].values
y = d.iloc[:, 0].values
print(y)

#there are 11 unique classes for classification
print(np.unique(y, return_counts=True))

['Student loan' 'Credit card or prepaid card' 'Mortgage' ...
 'Payday loan, title loan, or personal loan' 'Mortgage'
 'Credit reporting, credit repair services, or other personal consumer reports']
(array(['Bank account or service', 'Checking or savings account',
       'Consumer Loan', 'Credit card', 'Credit card or prepaid card',
       'Credit reporting',
       'Credit reporting, credit repair services, or other personal consumer reports',
       'Debt collection',
       'Money transfer, virtual currency, or money service',
       'Money transfers', 'Mortgage', 'Other financial service',
       'Payday loan', 'Payday loan, title loan, or personal loan',
       'Prepaid card', 'Student loan', 'Vehicle loan or lease',
       'Virtual currency'], dtype=object), array([14885, 10141,  9473, 18838, 17048, 31588, 74460, 77742,  4550,
        1497, 49451,   292,  1747,  3453,  1450, 19610,  4523,    16]))


In [0]:
#converts into unique array with single positive token thus tokenizing it ,giving 200 words at time,neclecting punctuation and converting to lowercase
tk = Tokenizer(num_words=200, filters = '!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n',lower=True, split=" ")
tk.fit_on_texts(x)
x = tk.texts_to_sequences(x)
x = sequence.pad_sequences(x, maxlen=200)
print(x)

In [0]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder# assigns unique value to each and used as a label
labelencoder_Y = LabelEncoder()
y = labelencoder_Y.fit_transform(y)
print(y)
print(np.unique(y, return_counts=True))

[15  4 10 ... 13 10  6]
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17]), array([14885, 10141,  9473, 18838, 17048, 31588, 74460, 77742,  4550,
        1497, 49451,   292,  1747,  3453,  1450, 19610,  4523,    16]))


In [0]:
from keras import utils as np_utils #converts to vector
y = np_utils.to_categorical(y, num_classes=None)

print(y)

[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [0]:
np.random.seed(200)
indices = np.arange(len(x))
np.random.shuffle(indices)
x = x[indices]
y = y[indices]


In [0]:
print(x)
print(y)

[[  0   0   0 ... 169   6   6]
 [  0   0   0 ...   1   1   1]
 [  0   0   0 ...  34  17 121]
 ...
 [  2 157  47 ...  19  12 139]
 [  0   0   0 ...  17  39  46]
 [  0   0   0 ...  17  28 160]]
[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [0]:
index_from=3
start_char = 1
if start_char is not None:
        x = [[start_char] + [w + index_from for w in x1] for x1 in x]
elif index_from:
        x = [[w + index_from for w in x1] for x1 in x]

In [0]:
print(x)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [0]:
num_words = None
if not num_words:
        num_words = max([max(x1) for x1 in x])
        
oov_char = 2
skip_top = 0
# by convention, use 2 as OOV word
# reserve 'index_from' (=3 by default) characters:
# 0 (padding), 1 (start), 2 (OOV)
if oov_char is not None:
        x = [[w if (skip_top <= w < num_words) else oov_char for w in x1] for x1 in x]
else:
        x = [[w for w in x1 if (skip_top <= w < num_words)] for x1 in x]
        
# split test and train data
test_split = 0.2
idx = int(len(x) * (1 - test_split))
x_train, y_train = np.array(x[:idx]), np.array(y[:idx])
x_test, y_test = np.array(x[:idx]), np.array(y[:idx]) #######################

print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)
print(y)

NameError: ignored

In [0]:
x_train = sequence.pad_sequences(x_train, maxlen=201)
x_test = sequence.pad_sequences(x_test, maxlen=201)
print('x_train shape:', x_train.shape)
print('x_test shape:', x_test.shape)


x_train shape: (272611, 201)
x_test shape: (68153, 201)


In [0]:
max_features = 1000
maxlen = 201
embedding_dims = 50
filters = 250
kernel_size = 3
hidden_dims = 250


# CNN with max pooling imeplementation 
print('Build model...')
model = Sequential()
# we start off with an efficient embedding layer which maps
# our vocab indices into embedding_dims dimensions
model.add(Embedding(max_features,
                    embedding_dims,
                    input_length=maxlen))
model.add(Dropout(5.0))

Build model...


In [0]:
# we add a Convolution1D, which will learn filters
# word group filters of size filter_length:
model.add(Conv1D(filters,
                 kernel_size,
                 padding='valid',
                 activation='relu',
                 strides=1))
# we use max pooling:
model.add(GlobalMaxPooling1D())

In [0]:


# We add a vanilla hidden layer:
model.add(Dense(hidden_dims))
model.add(Dropout(5.0))
model.add(Activation('relu'))



In [0]:
# We project onto a single unit output layer, and squash it with a sigmoid:
model.add(Dense(11))
model.add(Activation('softmax'))

In [0]:
model.compile(loss='sparse_categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])


In [0]:

model.fit(x_train, y_train,
          batch_size=32,
          epochs=50,
          validation_data=(x_test, y_test))

ValueError: ignored

In [0]:
# We project onto a single unit output layer, and squash it with a sigmoid:
model.add(Dense(11))
model.add(Activation('softmax'))

model.compile(loss='sparse_categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

model.fit(x_train, y_train,
          batch_size=32,
          epochs=50,
          validation_data=(x_test, y_test))

ValueError: ignored

In [0]:
max_features = 1000
maxlen = 201
embedding_dims = 50
filters = 250
kernel_size = 3
hidden_dims = 250


# CNN with max pooling imeplementation 
print('Build model...')
model = Sequential()
# we start off with an efficient embedding layer which maps
# our vocab indices into embedding_dims dimensions
model.add(Embedding(max_features,
                    embedding_dims,
                    input_length=maxlen))
model.add(Dropout(5.0))

# we add a Convolution1D, which will learn filters
# word group filters of size filter_length:
model.add(Conv1D(filters,
                 kernel_size,
                 padding='valid',
                 activation='relu',
                 strides=1))
# we use max pooling:
model.add(GlobalMaxPooling1D())

# We add a vanilla hidden layer:
model.add(Dense(hidden_dims))
model.add(Dropout(5.0))
model.add(Activation('relu'))


# We project onto a single unit output layer, and squash it with a sigmoid:
model.add(Dense(11))
model.add(Activation('softmax'))

model.compile(loss='sparse_categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

model.fit(x_train, y_train,
          batch_size=32,
          epochs=50,
          validation_data=(x_test, y_test))

Build model...


ValueError: ignored